openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: some great api...
  termsOfService: https://www.example.com
  contact:
    email: support@seb.se
    name: Support Team
    url: https://www.example.com/support
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: https://my-json-server.typicode.com/pixhula/api-server
    variables: {}
    description: my json server
  - url: http://localhost:{port}
    variables:
      port:
        default: '3000'
        enum:
          - '3000'
          - '8080'
        description: 3000 for test, 8080 for prod
    description: Local developing
paths:
  /users:
    summary: creates and returns users
    description: GET and POST users
    get:
      summary: fetches users
      description: returns users from server
      operationId: fetchUsers
      responses:
        '200':
          $ref: '#/components/responses/UserResponseBody'
        default:
          description: Default error sample response
      tags:
        - Users
    post:
      summary: create a new user
      description: store user on server
      operationId: createUser
      requestBody:
        $ref: '#/components/requestBodies/UserRequestBody'
      responses:
        '201':
          $ref: '#/components/responses/UserResponseBody'
      tags:
        - Users
  /users/{userId}:
    summary: User based operations
    description: GET, UPDATE AND DELETE a user
    parameters:
      - $ref: '#/components/parameters/UserId'
    get:
      summary: fetch a user
      description: returns a user from the server
      operationId: fetchUser
      responses:
        '200':
          $ref: '#/components/responses/UserResponseBody'
        default:
          description: Default error sample response
      tags:
        - Users
    patch:
      summary: update a user
      description: Updates server data for a user
      operationId: updateUser
      requestBody:
        $ref: '#/components/requestBodies/UserRequestBody'
      responses:
        '200':
          $ref: '#/components/responses/UserResponseBody'
        default:
          description: Default error sample response
      tags:
        - Users
    delete:
      summary: delete a user
      description: deletes user from database
      operationId: deleteUser
      responses:
        default:
          description: Default error sample response
      tags:
        - Users
components:
  parameters:
    UserId:
      name: userId
      in: path
      required: true
      description: user id
      schema: 
        type: string
        example: 6d8f2179-d568-4103-97d8-b3a90033b18a
    attempts:
      name: attempts
      in: path
      required: true
      description: attempts
      schema: 
        type: number
        example: 1
    OffSet:
      name: offset
      in: query
      required: false
      description: offset
      schema: 
        type: number
        example: 10
  responses:
    UserResponseBody:
      description: successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserArray'
  requestBodies:
    UserRequestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PostNewUser'
  schemas:
    UserArray:
      type: array
      items:
        $ref: '#/components/schemas/FullUser'
    PostNewUser:
      type: object
      properties:
        username:
          type: string
          example: john.doe@example.com
        age:
          type: integer
          example: 55
        active:
          type: boolean
          example: true
    FullUser:
      allOf:
        - type: object
          properties:
            id:
              type: string
              example: 6dba9a81-174c-4d9d-9b82-dd50126ed714
        - $ref: '#/components/schemas/PostNewUser'
