openapi: 3.0.1
info:
  title: My API
  version: '1.0'
  description: some great api...
  termsOfService: https://www.example.com
  contact:
    email: support@seb.se
    name: Support Team
    url: https://www.example.com/support
  license:
    name: License
    url: https://www.example.com/license
servers:
  - url: http://localhost:3000
    variables: {}
    description: local mock server
  - url: https://my-json-server.typicode.com/pixhula/api-server
    variables: {}
    description: my json server
paths:
  /users:
    summary: creates and returns users
    description: GET and POST users
    get:
      summary: fetches users
      description: returns users from server
      operationId: fetchUsers
      responses:
        '200':
          $ref: '#/components/responses/UserResponseBody'
        default:
          description: Default error sample response
      tags:
        - Users
    post:
      summary: create a new user
      description: store user on server
      operationId: createUser
      requestBody: 
        $ref: '#/components/requestBodies/UserRequestBody'
      responses:
        '201':
          $ref: '#/components/responses/UserResponseBody'
      tags:
        - Users
components:
  responses:
    UserResponseBody:
      description: successful request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/UserArray'
  requestBodies:
    UserRequestBody:
      required: true
      content: 
        application/json: 
          schema:
            $ref: '#/components/schemas/PostNewUser'
  schemas:
    UserArray:
      type: array
      items:
        $ref: '#/components/schemas/FullUser'
    PostNewUser:
      type: object
      properties: 
        username:
          type: string
          example: john.doe@example.com
        age:
          type: integer
          example: 55
        active:
          type: boolean
          example: true
    FullUser:
      allOf:
      - type: object
        properties:
          id:
            type: string
            example: 6dba9a81-174c-4d9d-9b82-dd50126ed714
      - $ref: '#/components/schemas/PostNewUser'
